### ISSUE TITLE
No such file or directory: 'outputs/validation/validation.pickle' Help

### ISSUE THREAD

**Issue by ktj4820** [ThomasLech/CROHME_extractor#6]
> python extract_hog.py 5  

==============================================================
 # Script flags: <hog_cell_size>

Restoring training set ...
Restoring test set ...
Traceback (most recent call last):
  File "extract_hog.py", line 44, in <module>
    with open(os.path.join(validation_dir, 'validation.pickle'), 'rb') as validation:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/validation/validation.pickle'
================================================================

**Comment by ThomasLech** [comment]
Hey, you just need to remove the line from the "extract_hog.py" script that is loading validation set. As far as I remember there is no validation set coming with the CROHME dataset, or there is, but the "extract.py" script doesn't extract the validation set anyways.

PRs solving this problems are welcome!

**Comment by youmizai** [comment]
hai ,IS your program seems to be unable to use the CROHME2016? how to solved this problem

**Comment by ThomasLech** [comment]
My scripts don't support the CROHME2016 database as it came out relatively recently.

**Comment by ThomasLech** [comment]
Please submit a PR with a support for CROHME2016 datasets. I'll review & merge as soon as possible.
